### ISSUE TITLE
"conda install from conda-forge" leads to the installation of older versions of pysal?

### ISSUE THREAD

**Issue by weikang9009** [conda-forge/pysal-feedstock#24] opened 2020-02-24 22:41 UTC
`conda install -c conda-forge pysal` will install pysal 1.14.4.post2 rather than the newest version 2.2.0 on my mac (I am on Python 3.7).

On [the conda-forge page for pysal](https://anaconda.org/conda-forge/pysal), multiple versions of `pysal` are listed as the results of the conda install. Not sure why this is the case. 
![image](https://user-images.githubusercontent.com/7359284/75197574-6e9d0200-5713-11ea-8ea3-1ceb72add951.png)

**Comment by ocefpaf** [comment] 2020-02-26 17:51
Can you try `conda install -c conda-forge pysal will install pysal=2.2.0` I believe the problem is something to do with a bad version comparison and conda believe that `1.14.4.post2` is greater than `2.2.0`.

**Comment by weikang9009** [comment] 2020-02-27 00:00
Thanks for the response. Just tried on another machine which has never installed `pysal` before: 
`conda install -c conda-forge pysal` installs `2.2.0`. The older version `1.14.4.post2` was installed on my machine with `conda install -c conda-forge pysal` probably because of the cached directory. 

But it would be nice if the conda-forge page for pysal only displays the latest version.

**Comment by ocefpaf** [comment] 2020-02-27 12:29
> Thanks for the response. Just tried on another machine which has never installed `pysal`

That is why I removed the bad version names, with the `.post`.

> before:
> `conda install -c conda-forge pysal` installs `2.2.0`. The older version `1.14.4.post2` was installed on my machine with `conda install -c conda-forge pysal` probably because of the cached directory.

Could be cache but I fixed this after you opened to issue.

> But it would be nice if the conda-forge page for pysal only displays the latest version.

It does. The problem is that conda cannot understand that `1.14.post2` is < `2.2.0`. I believe this bug was fixed a some point and maybe you have an old conda version. Still, we don't need post builds in conda forge. (Most post builds a to fix PyPI deployments and not the package per se.)

Closing this as solved. Let me know if you have any other questions.

**Closed as completed by ocefpaf** 2020-02-27 12:29 UTC
